### ISSUE TITLE
Problems with IPython 5

### ISSUE THREAD

**Issue by nightmarebadger** [inducer/pudb#193]
Trying to use `pudb` with `IPython 5` has been causing me problems. 

Pressing `!` to go to `ipdb` works fine for the first time, but getting out of the shell and trying in again doesn't do anything. Have not thoroughly tested but everything seems fine on the first try, and quitting `pudb` and restarting it makes it fine again (but again only for one run). 

I guess it has something to do with the massive changes introduced in IPython 5?

**Comment by inducer** [comment]
I can reproduce this. @minrk, any clue why this code:

https://github.com/inducer/pudb/blob/f46002a76fac99be1432b9a541aaf464f3e4e397/pudb/shell.py#L154

only works once to enter IPython?

**Comment by immerrr** [comment]
Another problem with IPython is that the new & fancy completion seems broken.

**Comment by minrk** [comment]
@inducer I can't think of why it would work only once, but I'll look into it.

**Comment by JohnLunzer** [comment]
I can also report to that IPython 5 completions do not work for me

**Comment by minrk** [comment]
Found it: turns out you can't start IPython 5 more than once because of some leftover state. Fixed by https://github.com/ipython/ipython/pull/9843.

**Comment by nightmarebadger** [comment]
@minrk This does not fix the completions problem though right?

For me the new and fancy completions work for some things like `for`, `import` etc., but not for anything "live" (variables, imported packages, ... ).

**Comment by minrk** [comment]
@nightmarebadger it didn't, but it does now.

**Comment by jeffwidman** [comment]
So can this be closed?

**Comment by JohnLunzer** [comment]
pudb is working correctly now as of IPython 5.1.0, resolving this issue. This should be closed.
